version: "3.9"

services:
  webserver:
    image: ${REGISTRY}/${REGISTRY_IMAGE}:latest
    container_name: vlecture-api
    restart: on-failure:3
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: vlecture_db
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - vlecture_db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  vlecture_db:
